### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by riazatkabir** [zabir-nabil/bangla-tts#14]
![1](https://user-images.githubusercontent.com/72545896/146693741-420dbf1a-748c-4b93-90d6-6aeea041b44e.PNG)

**Comment by riazatkabir** [comment]
Where is the problem?

**Comment by riazatkabir** [comment]
And whre are the audio files.

**Comment by zabir-nabil** [comment]
Please use `tensorflow 1.14` as suggested in the requirements.txt file. Use a virtual environment preferably with conda.
