### ISSUE TITLE
Data loss error

### ISSUE THREAD

**Issue by Subho95** [zabir-nabil/bangla-tts#3]
The above error is being thrown when we try to load the weight from the uploaded file.

**Comment by zabir-nabil** [comment]
Can you post the full error message? Usually, this can happen if you downloaded an incomplete file. Also add the script name which gives the error.

**Comment by Subho95** [comment]
INFO:tensorflow:Restoring parameters from model1/model_gs_301k.data-00000-of-00001
---------------------------------------------------------------------------
DataLossError                             Traceback (most recent call last)
E:\Python Anaconda\lib\site-packages\tensorflow\python\client\session.py in _do_call(self, fn, *args)
   1355     try:
-> 1356       return fn(*args)
   1357     except errors.OpError as e:

E:\Python Anaconda\lib\site-packages\tensorflow\python\client\session.py in _run_fn(feed_dict, fetch_list, target_list, options, run_metadata)
   1340       return self._call_tf_sessionrun(
-> 1341           options, feed_dict, fetch_list, target_list, run_metadata)
   1342 

E:\Python Anaconda\lib\site-packages\tensorflow\python\client\session.py in _call_tf_sessionrun(self, options, feed_dict, fetch_list, target_list, run_metadata)
   1428         self._session, options, feed_dict, fetch_list, target_list,
-> 1429         run_metadata)
   1430 

DataLossError: Unable to open table file model1\model_gs_301k.data-00000-of-00001: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
	 [[{{node save/RestoreV2}}]]

During handling of the above exception, another exception occurred:

DataLossError                             Traceback (most recent call last)
<ipython-input-7-fa6a7ceac08a> in <module>
    294 
    295 if __name__ == '__main__':
--> 296     p=generate(["আমার সোনার বাংলা আমি তোমাকে ভালোবাসি"])
    297     #generate(["আমার সোনার বাংলা আমি তোমাকে ভালোবাসি", "আমার নাম জাবির আল নাজি নাবিল", "I am still not a great speaker", "This is just a test"], 'static')
    298     #generate_long("বাংলাদেশে গত ২৪ ঘণ্টায় ৩০৬ জন কোভিড-১৯ আক্রান্ত হয়েছেন। এই সময়ের মধ্যে মৃত্যু হয়েছে ৯ জনের। এ নিয়ে দেশটিতে মোট আক্রান্ত হলেন ২১৪৪। আর করোনা ভাইরাসে আক্রান্ত হয়ে মৃত্যু হয়েছে ৮৪ জনের। নতুন করে ৮ জনের পরীক্ষা করার পর করোনা ভাইরাসের উপস্থিতি পাওয়া যায়নি। এনিয়ে মোট ৬৬ জন সুস্থ হলেন।")

<ipython-input-7-fa6a7ceac08a> in generate(text_arr, save_path)
    144 
    145         #saver1.restore(sess, tf.train.latest_checkpoint("model1"))
--> 146         saver1.restore(sess, "model1/model_gs_301k.data-00000-of-00001")
    147         print("Model 1 loaded!")
    148 

E:\Python Anaconda\lib\site-packages\tensorflow\python\training\saver.py in restore(self, sess, save_path)
   1284       else:
   1285         sess.run(self.saver_def.restore_op_name,
-> 1286                  {self.saver_def.filename_tensor_name: save_path})
   1287     except errors.NotFoundError as err:
   1288       # There are three common conditions that might cause this error:

E:\Python Anaconda\lib\site-packages\tensorflow\python\client\session.py in run(self, fetches, feed_dict, options, run_metadata)
    948     try:
    949       result = self._run(None, fetches, feed_dict, options_ptr,
--> 950                          run_metadata_ptr)
    951       if run_metadata:
    952         proto_data = tf_session.TF_GetBuffer(run_metadata_ptr)

E:\Python Anaconda\lib\site-packages\tensorflow\python\client\session.py in _run(self, handle, fetches, feed_dict, options, run_metadata)
   1171     if final_fetches or final_targets or (handle and feed_dict_tensor):
   1172       results = self._do_run(handle, final_targets, final_fetches,
-> 1173                              feed_dict_tensor, options, run_metadata)
   1174     else:
   1175       results = []

E:\Python Anaconda\lib\site-packages\tensorflow\python\client\session.py in _do_run(self, handle, target_list, fetch_list, feed_dict, options, run_metadata)
   1348     if handle is None:
   1349       return self._do_call(_run_fn, feeds, fetches, targets, options,
-> 1350                            run_metadata)
   1351     else:
   1352       return self._do_call(_prun_fn, handle, feeds, fetches)

E:\Python Anaconda\lib\site-packages\tensorflow\python\client\session.py in _do_call(self, fn, *args)
   1368           pass
   1369       message = error_interpolation.interpolate(message, self._graph)
-> 1370       raise type(e)(node_def, op, message)
   1371 
   1372   def _extend_graph(self):

DataLossError: Unable to open table file model1\model_gs_301k.data-00000-of-00001: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
	 [[node save/RestoreV2 (defined at <ipython-input-7-fa6a7ceac08a>:141) ]]

**Comment by Subho95** [comment]
The above is the error that I am getting. Another error that I was getting was during the model download. I was getting the below error when I tried to download the model through the code. I fixed it by downloading the model manually from the given URL and then replacing it in the correct folder. Even the saver1.restore(sess, tf.train.latest_checkpoint("model1")) was not able to find the last checkpoint and returned "None" that resulted in an error, which I resolved by giving the absolute path "model1/model_gs_301k.data-00000-of-00001" to the restore function.

---------------------------------------------------------------------------
HTTPError                                 Traceback (most recent call last)
<ipython-input-1-7a2298d11c6d> in <module>
      1 import wget
----> 2 wget.download("https://gitlab.com/zabir-nabil/bangla_tts_weights/raw/master/model_gs_300k.data-00000-of-00001")

E:\Python Anaconda\lib\site-packages\wget.py in download(url, out, bar)
    524     else:
    525         binurl = url
--> 526     (tmpfile, headers) = ulib.urlretrieve(binurl, tmpfile, callback)
    527     filename = detect_filename(url, out, headers)
    528     if outdir:

E:\Python Anaconda\lib\urllib\request.py in urlretrieve(url, filename, reporthook, data)
    245     url_type, path = splittype(url)
    246 
--> 247     with contextlib.closing(urlopen(url, data)) as fp:
    248         headers = fp.info()
    249 

E:\Python Anaconda\lib\urllib\request.py in urlopen(url, data, timeout, cafile, capath, cadefault, context)
    220     else:
    221         opener = _opener
--> 222     return opener.open(url, data, timeout)
    223 
    224 def install_opener(opener):

E:\Python Anaconda\lib\urllib\request.py in open(self, fullurl, data, timeout)
    529         for processor in self.process_response.get(protocol, []):
    530             meth = getattr(processor, meth_name)
--> 531             response = meth(req, response)
    532 
    533         return response

E:\Python Anaconda\lib\urllib\request.py in http_response(self, request, response)
    639         if not (200 <= code < 300):
    640             response = self.parent.error(
--> 641                 'http', request, response, code, msg, hdrs)
    642 
    643         return response

E:\Python Anaconda\lib\urllib\request.py in error(self, proto, *args)
    567         if http_err:
    568             args = (dict, 'default', 'http_error_default') + orig_args
--> 569             return self._call_chain(*args)
    570 
    571 # XXX probably also want an abstract factory that knows when it makes

E:\Python Anaconda\lib\urllib\request.py in _call_chain(self, chain, kind, meth_name, *args)
    501         for handler in handlers:
    502             func = getattr(handler, meth_name)
--> 503             result = func(*args)
    504             if result is not None:
    505                 return result

E:\Python Anaconda\lib\urllib\request.py in http_error_default(self, req, fp, code, msg, hdrs)
    647 class HTTPDefaultErrorHandler(BaseHandler):
    648     def http_error_default(self, req, fp, code, msg, hdrs):
--> 649         raise HTTPError(req.full_url, code, msg, hdrs, fp)
    650 
    651 class HTTPRedirectHandler(BaseHandler):

HTTPError: HTTP Error 403: Forbidden

**Comment by zabir-nabil** [comment]
delete the repository, do a clean clone, and run with a stable internet connection. The files are large (>500mb) so make sure they are downloaded properly.

**Comment by Subho95** [comment]
Issue resolved. Problem was probably because I was creating a ipynb file for the above codes with anaconda. When only running the .py file, ot ran smoothly. Thanks.

**Comment by nafeesmahbub** [comment]
Is it possible to train with new domain data from an already build model.

**Comment by zabir-nabil** [comment]
Yes, you can try transfer learning. @nafeesmahbub
