### ISSUE TITLE
different model

### ISSUE THREAD

**Issue by nafeesmahbub** [zabir-nabil/bangla-tts#6]
Unable to open table file ./model1/checkpoint_13000: Data loss: not an stable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?

is possible to run with own model with tactron.

**Comment by zabir-nabil** [comment]
No, the inference script is specifically written for the model I'm using and won't work on tacotron.

**Comment by nafeesmahbub** [comment]
Is it possible to train it with own custom dataset of about 32 Hrs using training script.

**Comment by zabir-nabil** [comment]
Yes, it's definitely possible, you have to write and modify the training script accordingly.
